
package us.gov.treasury.irs.srv.getepdbulkrequest;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.0.1
 * 2014-07-21T12:31:09.147-05:00
 * Generated source version: 3.0.1
 */

@WebFault(name = "ErrorMessageDetail", targetNamespace = "urn:us:gov:treasury:irs:common")
public class Fault extends Exception {
    
    private us.gov.treasury.irs.epd.bulkfileproc.common.ErrorMessageDetailType errorMessageDetail;

    public Fault() {
        super();
    }
    
    public Fault(String message) {
        super(message);
    }
    
    public Fault(String message, Throwable cause) {
        super(message, cause);
    }

    public Fault(String message, us.gov.treasury.irs.epd.bulkfileproc.common.ErrorMessageDetailType errorMessageDetail) {
        super(message);
        this.errorMessageDetail = errorMessageDetail;
    }

    public Fault(String message, us.gov.treasury.irs.epd.bulkfileproc.common.ErrorMessageDetailType errorMessageDetail, Throwable cause) {
        super(message, cause);
        this.errorMessageDetail = errorMessageDetail;
    }

    public us.gov.treasury.irs.epd.bulkfileproc.common.ErrorMessageDetailType getFaultInfo() {
        return this.errorMessageDetail;
    }
}
